apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-d
  labels:
    app: readiness-d
spec:
  replicas: 5
  selector:
    matchLabels:
      app: readiness-d
  template:
    metadata:
      labels:
        app: readiness-d
    spec:
      containers:
        - name: readiness
          image: k8s.gcr.io/busybox
          args:
            - /bin/sh
            - -c
            - sleep 15; touch /tmp/healthy; sleep 600
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 10
            periodSeconds: 5
      terminationGracePeriodSeconds: 0



