version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory

  # https://github.com/docker/distribution/issues/1326
  delete: # https://docs.docker.com/registry/configuration/#delete
    enabled: true

  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3