version: '3.5'
services:
  mysql:
    build:
      context: jen
      dockerfile: Dockerfile
    container_name: jen
    ports:
      - "8888:80"
#    environment:
#      - MYSQL_ROOT_PASSWORD=$PROTECTED_MYSQL_PASS
#      - MYSQL_ROOT_HOST=%
#    networks:
#      - "${PROJECT_NAME}-network"
#    volumes:
#      - ./mysql_db/$PROJECT_NAME:/var/lib/mysql
##        deploy:
##            resources:
##                limits:
###                    cpus: '0.50'
###                    memory: 50M
##                    memory: 5G
##                reservations:
###                    cpus: '0.25'
##                    memory: 5G
#
#networks:
#  ${PROJECT_NAME}-network:
#    name: ${PROJECT_NAME}-network