apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hubaml
#  namespace: nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-sc-for-cluster



#    ---
#    kind: PersistentVolumeClaim
#    apiVersion: v1
#    metadata:
#      name: test-dynamic-volume-claim
#    spec:
#      storageClassName: "nfs-sc-for-cluster"
#      accessModes:
#        - ReadWriteOnce
#      resources:
#        requests:
#          storage: 100Mi
