apiVersion: apps/v1
kind: Deployment
metadata:
  name: piiapp
  labels:
    app: piiapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piiapp
  template:
    metadata:
      labels:
        app: piiapp
    spec:
      containers:
        - name: piiapp
          image: 'sdpii/piiapp:0.0.18'
          ports:
            - containerPort: 80
