kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"

    # https://www.digitalocean.com/docs/kubernetes/how-to/configure-load-balancers/
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin" # least_connections
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "40f702ff-88b3-47b0-b849-865b315c8fa1"

    # kubectl get svc ingress-nginx -n ingress-nginx  -o jsonpath="{.metadata.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-algorithm}"
    # kubectl annotate --overwrite -f loadbalancer.yaml service.beta.kubernetes.io/do-loadbalancer-algorithm=least_connections
    # kubectl get svc ingress-nginx -n ingress-nginx  -o jsonpath="{.metadata.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-certificate-id}"
    # kubectl annotate --overwrite -f loadbalancer.yaml service.beta.kubernetes.io/do-loadbalancer-algorithm=round_robin
    # kubectl get svc ingress-nginx -n ingress-nginx  -o jsonpath="{.metadata.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-certificate-id}"
    # kubectl annotate --overwrite -f loadbalancer.yaml service.beta.kubernetes.io/do-loadbalancer-certificate-id=40f702ff-88b3-47b0-b849-865b315c8fa1

    # kubectl get -f loadbalancer.yaml -o jsonpath="{.metadata.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-certificate-id}"
spec:
  #externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80

# ---

# examples:
#     https://github.com/digitalocean/digitalocean-cloud-controller-manager/tree/master/docs/controllers/services/examples
# main doc: How to Add Load Balancers to Kubernetes Clusters
#     https://www.digitalocean.com/docs/kubernetes/how-to/add-load-balancers/
# main doc: How to Configure SSL Termination
#     https://www.digitalocean.com/docs/networking/load-balancers/how-to/ssl-termination/#add-an-ssl-certificate
# generating do cert using cli
# https://blog.andrewsomething.com/2019/04/04/external-dns-with-ssl-on-k8s/
