version: '3.0'
 
services:
  ownregistry:
#    image: registry:2.7.1
    build:
      context: image
      dockerfile: Dockerfile
    container_name: docker-registry
    volumes:
      # - registry:/var/lib/registry
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/docker/registry:/var/lib/registry
      - ~/.htpasswd:/htpasswd
    ports:
      - "443:5000"
    restart: unless-stopped
    env_file:
      - .env

volumes:
  registry: