version: '3.0'
 
services:
  ownregistry:
#    image: registry:2.7.1
    build:
      context: image
      dockerfile: Dockerfile
    container_name: docker-registry
    volumes:



      - /etc/letsencrypt:/etc/letsencrypt   # commented with switching from 443 to 80



      - /var/lib/docker/registry:/var/lib/registry
      - ~/.htpasswd:/htpasswd
      
      # Not needed anymore as we have config already in image/ folder and injected in Dockerfile
      # - ./registry-config/config.yml:/etc/docker/registry/config.yml:ro
    ports:
      #      - "443:5000"
      # since we handled jenkis with https we had to add nginx
      # having nginx we will use certificate on nginx to provide https to docker registry
      - "127.0.0.1:8090:5000"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - registry-ui-net

  ownregistry-ui:
    image: joxit/docker-registry-ui:static
    restart: unless-stopped
    ports:  
      - 8181:80 
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=https://ownregistry:5000
      - DELETE_IMAGES=true
    depends_on:
      - ownregistry
    container_name: docker-registry-ui
    networks:
      - registry-ui-net

volumes:
  registry:

networks:
  registry-ui-net: