apiVersion: v1
kind: Pod
metadata:
  name: podapp
spec:
  containers:
    - name: podapp
      image: "docker-registry.phaseiilabs.com/tapp:0.0.8"
#      imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: regcred